name = "Tenegood SMP 2"
author = "Kirbob, Mega"
version = "0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7102ed7bbb2daf8943cda889d24e206eeb916f9de44394626fa521928562454d"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
