name = "Tenegood SMP 2"
author = "Kirbob, Mega"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "172bec858f1586d8a3cf39ee91f2077e47bc43388e8dc555af149ff796c9f1e5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
